import React, { useState } from 'react';
import axios from 'axios';
import { jsPDF } from 'jspdf';
import { AlertCircle, CheckCircle, Database, FileText, Download } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const API_URL = import.meta.env.VITE_API_URL;



const PredictionPage = () => {
    const [formData, setFormData] = useState({
        age: 50,
        gender: 'Female',
        height: 165,
        weight: 70,
        ap_hi: 120,
        ap_lo: 80,
        cholesterol: 1,
        gluc: 1,
        smoke: 0,
        alco: 0,
        active: 1
    });

    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: name === 'gender' ? value : Number(value)
        }));
    };

    const calculateBMI = () => {
        if (formData.height === 0) return 0;
        return (formData.weight / Math.pow(formData.height / 100, 2)).toFixed(1);
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError(null);
        setResult(null);

        try {
            const response = await axios.post(`${import.meta.env.VITE_CARDIO_API}/predict`, formData);
            setResult(response.data);
            setTimeout(() => {
                document.getElementById('result-section')?.scrollIntoView({ behavior: 'smooth' });
            }, 100);
        } catch (err) {
            setError('Failed to connect to the prediction engine. Please ensure the server is running.');
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const generatePDF = () => {
        if (!result) return;

        const doc = new jsPDF();
        const lineHeight = 10;
        let y = 20;

        // Header
        doc.setFontSize(22);
        doc.setTextColor(37, 99, 235); // Primary Blue
        doc.text("CardioPredict Assessment Report", 20, y);
        y += lineHeight * 1.5;

        // Date
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, y);
        y += lineHeight * 2;

        // Patient Details
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text("Patient Metrics", 20, y);
        y += lineHeight;

        doc.setFontSize(11);
        const metrics = [
            `Age: ${formData.age} years`,
            `Gender: ${formData.gender}`,
            `BMI: ${calculateBMI()}`,
            `Blood Pressure: ${formData.ap_hi}/${formData.ap_lo}`,
            `Cholesterol Level: ${formData.cholesterol === 1 ? 'Normal' : formData.cholesterol === 2 ? 'Above Normal' : 'Well Above Normal'}`,
            `Glucose Level: ${formData.gluc === 1 ? 'Normal' : formData.gluc === 2 ? 'Above Normal' : 'Well Above Normal'}`,
            `Smoker: ${formData.smoke ? 'Yes' : 'No'}`,
            `Alcohol Intake: ${formData.alco ? 'Moderate/High' : 'None/Low'}`,
            `Physical Activity: ${formData.active ? 'Active' : 'Inactive'}`
        ];

        metrics.forEach(metric => {
            doc.text(metric, 25, y);
            y += 8;
        });

        y += lineHeight;

        // Result
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text("Analysis Result", 20, y);
        y += lineHeight;

        doc.setFontSize(12);
        if (result.prediction) {
            doc.setTextColor(220, 38, 38); // Red
            doc.text(`RISK DETECTED`, 20, y);
        } else {
            doc.setTextColor(22, 163, 74); // Green
            doc.text(`LOW RISK`, 20, y);
        }
        y += 8;

        doc.setTextColor(0);
        doc.text(`Probability: ${(result.probability * 100).toFixed(1)}%`, 20, y);
        y += lineHeight;
        doc.text(`Analysis: ${result.message}`, 20, y);

        y += lineHeight * 2;

        // Disclaimer
        doc.setFontSize(8);
        doc.setTextColor(150);
        const disclaimer = "DISCLAIMER: This report is generated by an AI model for informational purposes only. It is not a medical diagnosis. Please consult a healthcare professional for accurate medical advice.";
        const splitDisclaimer = doc.splitTextToSize(disclaimer, 170);
        doc.text(splitDisclaimer, 20, y);

        doc.save("CardioPredict_Report.pdf");
    };

    return (
        <div className="container" style={{ paddingBottom: '6rem' }}>
            <motion.div
                className="hero"
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                style={{ textAlign: 'center' }}
            >
                <h1>Predicting Heart Health<br /><span>With Precision</span></h1>
                <p>Leverage our advanced machine learning algorithms to assess your cardiovascular risk profile in seconds.</p>
            </motion.div>

            <div id="assessment" className="card">
                <div style={{ marginBottom: '2.5rem', textAlign: 'center' }}>
                    <h2 className="section-title" style={{ marginBottom: '0.5rem', fontSize: '1.75rem' }}>
                        Patient Assessment
                    </h2>
                    <p style={{ color: 'var(--text-secondary)' }}>Enter clinical metrics for instantaneous risk analysis.</p>
                </div>

                <form onSubmit={handleSubmit}>
                    <div className="form-grid">
                        <div className="input-wrapper">
                            <label>Age (years)</label>
                            <input type="number" name="age" value={formData.age} onChange={handleChange} min="10" max="100" />
                        </div>

                        <div className="input-wrapper">
                            <label>Gender</label>
                            <select name="gender" value={formData.gender} onChange={handleChange}>
                                <option value="Female">Female</option>
                                <option value="Male">Male</option>
                            </select>
                        </div>

                        <div className="input-wrapper">
                            <label>Height (cm)</label>
                            <input type="number" name="height" value={formData.height} onChange={handleChange} min="100" max="250" />
                        </div>

                        <div className="input-wrapper">
                            <label>Weight (kg)</label>
                            <input type="number" name="weight" value={formData.weight} onChange={handleChange} min="30" max="200" />
                        </div>

                        <div className="input-wrapper">
                            <label>Systolic BP (ap_hi)</label>
                            <input type="number" name="ap_hi" value={formData.ap_hi} onChange={handleChange} min="60" max="250" />
                        </div>

                        <div className="input-wrapper">
                            <label>Diastolic BP (ap_lo)</label>
                            <input type="number" name="ap_lo" value={formData.ap_lo} onChange={handleChange} min="40" max="150" />
                        </div>

                        <div className="input-wrapper">
                            <label>Cholesterol</label>
                            <select name="cholesterol" value={formData.cholesterol} onChange={handleChange}>
                                <option value="1">Normal</option>
                                <option value="2">Above Normal</option>
                                <option value="3">Well Above Normal</option>
                            </select>
                        </div>

                        <div className="input-wrapper">
                            <label>Glucose</label>
                            <select name="gluc" value={formData.gluc} onChange={handleChange}>
                                <option value="1">Normal</option>
                                <option value="2">Above Normal</option>
                                <option value="3">Well Above Normal</option>
                            </select>
                        </div>

                        <div className="input-wrapper">
                            <label>Smoking Status</label>
                            <select name="smoke" value={formData.smoke} onChange={handleChange}>
                                <option value="0">Non-Smoker</option>
                                <option value="1">Smoker</option>
                            </select>
                        </div>

                        <div className="input-wrapper">
                            <label>Alcohol Consumption</label>
                            <select name="alco" value={formData.alco} onChange={handleChange}>
                                <option value="0">None / Low</option>
                                <option value="1">Moderate / High</option>
                            </select>
                        </div>

                        <div className="input-wrapper">
                            <label>Physical Activity</label>
                            <select name="active" value={formData.active} onChange={handleChange}>
                                <option value="0">Inactive</option>
                                <option value="1">Active</option>
                            </select>
                        </div>

                        <div className="input-wrapper" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'flex-end' }}>
                            <div style={{ background: 'rgba(255,255,255,0.05)', padding: '0.875rem', borderRadius: '0.75rem', textAlign: 'center', border: '1px solid var(--border)' }}>
                                <div style={{ fontSize: '0.8rem', textTransform: 'uppercase', fontWeight: '700', color: 'var(--text-secondary)' }}>Calculated BMI</div>
                                <div style={{ fontWeight: '800', fontSize: '1.5rem', color: 'var(--text-main)' }}>{calculateBMI()}</div>
                            </div>
                        </div>
                    </div>

                    <div style={{ textAlign: 'center', marginTop: '2rem' }}>
                        <button type="submit" className="btn btn-primary" disabled={loading} style={{ minWidth: '240px' }}>
                            {loading ? <><div className="spinner"></div> Processing...</> : 'Run Predictive Model'}
                        </button>
                    </div>
                </form>

                <AnimatePresence>
                    {error && (
                        <motion.div
                            initial={{ opacity: 0, scale: 0.95 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0, scale: 0.95 }}
                            style={{ marginTop: '2rem', padding: '1rem', background: 'rgba(239, 68, 68, 0.2)', color: '#fca5a5', borderRadius: '1rem', textAlign: 'center', fontWeight: '500', border: '1px solid rgba(239, 68, 68, 0.3)' }}
                        >
                            {error}
                        </motion.div>
                    )}

                    {result && (
                        <motion.div
                            id="result-section"
                            className="result-container"
                            initial={{ opacity: 0, y: 30 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                        >
                            <div className={`result-card ${result.prediction ? 'result-high' : 'result-low'}`}>
                                {result.prediction ? <AlertCircle size={64} style={{ marginBottom: '1rem' }} /> : <CheckCircle size={64} style={{ marginBottom: '1rem' }} />}
                                <div className="result-title" style={{ fontSize: '2rem' }}>{result.message}</div>
                                <div className="result-prob" style={{ fontSize: '4.5rem', fontWeight: '800', margin: '0.5rem 0' }}>{(result.probability * 100).toFixed(1)}%</div>
                                <div className="result-desc" style={{ fontSize: '1.2rem', maxWidth: '600px', margin: '0 auto', opacity: 0.9 }}>
                                    Based on the Random Forest Classifier analysis of your provided clinical metrics.
                                </div>

                                <div style={{ marginTop: '2rem' }}>
                                    <button
                                        onClick={generatePDF}
                                        className="btn"
                                        style={{
                                            background: 'rgba(255, 255, 255, 0.2)',
                                            border: '1px solid rgba(255,255,255,0.3)',
                                            backdropFilter: 'blur(10px)',
                                            display: 'inline-flex',
                                            alignItems: 'center',
                                            gap: '0.5rem'
                                        }}
                                    >
                                        <Download size={20} /> Download Report
                                    </button>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            {/* Info Grid for Methodology & Legal */}
            <div id="methodology" style={{ marginTop: '6rem', marginBottom: '4rem' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '2rem' }}>

                    {/* Methodology */}
                    <div className="card">
                        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
                            <div style={{ background: 'rgba(59, 130, 246, 0.1)', padding: '0.75rem', borderRadius: '0.75rem', color: 'var(--primary)' }}>
                                <Database size={24} />
                            </div>
                            <h3 style={{ fontSize: '1.5rem', fontWeight: '800' }}>Methodology</h3>
                        </div>
                        <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
                            Our predictive engine is built upon a robust <strong>Random Forest Classifier</strong>, selected for its superior accuracy (73.23%) over traditional logistic regression models.
                        </p>
                        <p style={{ color: 'var(--text-secondary)' }}>
                            The model processes key health indicators through a decision ensemble, reducing overfitting and handling non-linear relationships between risk factors like age, BMI, and systolic blood pressure more effectively.
                        </p>
                    </div>

                    {/* Legal */}
                    <div id="legal" className="card">
                        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
                            <div style={{ background: 'rgba(239,68,68,0.1)', padding: '0.75rem', borderRadius: '0.75rem', color: 'var(--danger)' }}>
                                <FileText size={24} />
                            </div>
                            <h3 style={{ fontSize: '1.5rem', fontWeight: '800' }}>Legal & Medical Disclaimer</h3>
                        </div>
                        <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
                            <strong>Not Sound Medical Advice:</strong> This application is a statistical tool for informational purposes only. It is NOT a substitute for professional medical diagnosis, treatment, or advice.
                        </p>
                        <p style={{ color: 'var(--text-secondary)' }}>
                            <strong>Data Privacy:</strong> All computations are performed locally or securely transmitted. No personal health information (PHI) is permanently stored on our servers. Consult your physician for a clinically validated risk assessment.
                        </p>
                    </div>

                </div>
            </div>
        </div>
    );
};

export default PredictionPage;
